name: ELT Boardgames API

on:
  schedule:
    - cron: '0 10 * * *'  # This schedule runs the workflow every day at 10:00AM UTC

  workflow_dispatch:

jobs:
  elt:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Packages
        run: pip3 install -r requirements.txt

      - name: Get Boardgames Data
        run: python boardgames.py

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated update